version: '3.8'

services:
  bot:
    container_name: personal-bot
    image: "node:14"
    user: "node"
    working_dir: /home/node/bot
    volumes:
      - ./:/home/node/bot
    command: bash -c "npm i && node ."
    ports:
      - 8000:8000